# Generated by Django 5.2.1 on 2025-05-29 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producturl',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='producturl',
            name='last_price_currency',
        ),
        migrations.AddField(
            model_name='wishlistedproduct',
            name='last_json_ld',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='wishlistedproduct',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='wishlists.wishlist'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(choices=[('EUR', 'Eur'), ('USD', 'Usd'), ('CLP', 'Clp')], default='CLP')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='wishlists.producturl')),
            ],
        ),
    ]
