# Generated by Django 5.2.1 on 2025-05-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_remove_producturl_last_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producturl',
            name='description',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='producturl',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='producturl',
            name='name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
