# Generated by Django 5.2.1 on 2025-05-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_producturl_description_producturl_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistedproduct',
            name='description',
            field=models.CharField(null=True),
        ),
    ]
