# Generated by Django 5.2.1 on 2025-05-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0004_wishlistedproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistedproduct',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
