# Generated by Django 5.2.1 on 2025-05-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0005_wishlistedproduct_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='comment',
            field=models.CharField(null=True),
        ),
    ]
